// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7vbu2tRSZX-k0l2XM-lvDRkrtaPQHauE',
    appId: '1:111153909184:android:d0c2e4a45e47aede6b0c25',
    messagingSenderId: '111153909184',
    projectId: 'admin-app-1f284',
    storageBucket: 'admin-app-1f284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_cqui4lwsUNYv48lNPelocKrmIYbBkYM',
    appId: '1:111153909184:ios:a2ea064c2ffe3d286b0c25',
    messagingSenderId: '111153909184',
    projectId: 'admin-app-1f284',
    storageBucket: 'admin-app-1f284.firebasestorage.app',
    androidClientId: '111153909184-l8bvi5sjc33jr4u557gg3g6iltnkn4de.apps.googleusercontent.com',
    iosClientId: '111153909184-hm6fdqjtu7v6h389ucv9us7qsl3kglg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionClientApp',
  );

}